In [2]:
import pyspiel

In [3]:
game=pyspiel.load_game("mpg(max_moves=50,max_size=100,generator=usgnp,generator_params=30 30 0.3 0.7 -1 1,padding=false,representation=normal)")

In [4]:
state=game.new_initial_environment_state()

In [5]:
state.observation_tensor_shapes_list()

[[30, 30, 2], [1]]

In [6]:
state.count_edges()

485

In [7]:
state.graph_size()

30

In [8]:
E.shape

NameError: name 'E' is not defined

In [9]:
E=E.reshape(state.observation_tensor_shapes_list()[0])

E[:,:,1]

NameError: name 'E' is not defined

In [31]:
state.apply_action(2)

In [32]:
state

13085936220915563836

In [53]:
import numpy as np
A=np.array(state.observation_tensor())
E,s=A[:-1],A[-1]

In [57]:
E=E.reshape(state.observation_tensor_shapes_list()[0])
E[:,:,0]

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.]])

In [19]:
import pandas as pd
df=pd.read_json("stats.jsonl",lines=True)

In [20]:
df

0  \
0                                                 {}   
1                                                 {}   
2  {'start_time': '2023-06-26T00:45:36.482062', '...   
3  {'start_time': '2023-06-26T00:47:18.853107', '...   
4  {'start_time': '2023-06-26T00:49:02.368419', '...   
5  {'start_time': '2023-06-26T00:50:46.122679', '...   
6  {'start_time': '2023-06-26T00:52:29.063244', '...   
7  {'start_time': '2023-06-26T00:54:10.909819', '...   
8  {'start_time': '2023-06-26T00:55:53.082160', '...   

                                                   1  \
0                                                 {}   
1                                                 {}   
2  {'start_time': '2023-06-26T00:45:36.552605', '...   
3  {'start_time': '2023-06-26T00:47:19.672664', '...   
4  {'start_time': '2023-06-26T00:49:02.859706', '...   
5  {'start_time': '2023-06-26T00:50:44.802517', '...   
6  {'start_time': '2023-06-26T00:52:27.951881', '...   
7  {'start_time': '2023-06-26T00:54:09.628702', '...   
8  {'start_time': '2023-06-26T00:55:51.948519', '...   

                                                   2  
0                                                 {}  
1                                                 {}  
2  {'start_time': '2023-06-26T00:45:36.513515', '...  
3  {'start_time': '2023-06-26T00:47:18.744794', '...  
4  {'start_time': '2023-06-26T00:49:00.273266', '...  
5  {'start_time': '2023-06-26T00:50:42.113778', '...  
6  {'start_time': '2023-06-26T00:52:23.545262', '...  
7  {'start_time': '2023-06-26T00:54:06.049684', '...  
8  {'start_time': '2023-06-26T00:55:48.275617', '...

In [1]:
import pyspiel 
from mpg.games.mpg import MeanPayoffGraph
G=MeanPayoffGraph()
G.add_edge(0,1,2)
G.add_edge(1,0,1)

In [42]:
game=pyspiel.load_game("mpg(max_repeats=3,max_size=2,generator=gnp,generator_params=50 1 -1 1)")
state=game.new_initial_state()

In [11]:
import open_spiel.python.algorithms.alpha_zero_mpg.bots as mpg_bots
import open_spiel.python.algorithms.mcts as mcts

2023-06-28 13:02:23.665095: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 13:02:24.237729: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [12]:
uct_c=1
max_simulations=1000
evaluator_=mcts.RandomRolloutEvaluator()
noise=(1,1)
solve=False
bot=mcts.MCTSBot(
        game,
        uct_c,
        max_simulations,
        evaluator_,
        solve=solve,
        dirichlet_noise=None,
        child_selection_fn=mcts.SearchNode.puct_value,
        verbose=False,
        dont_return_chance_node=True)

In [13]:
state.apply_action12)

OpenSpiel exception: /home/ramizouari/Academic/AI/MeanPayOffGames/open_spiel/open_spiel/games/mpg/mpg.cc:139 CHECK_TRUE(environment->graph[current_state].count(move))


SpielError: /home/ramizouari/Academic/AI/MeanPayOffGames/open_spiel/open_spiel/games/mpg/mpg.cc:139 CHECK_TRUE(environment->graph[current_state].count(move))

In [110]:
state=game.new_initial_environment_state()
state.current_player()

0

In [111]:

root=bot.mcts_search(state)

root.total_reward / root.explore_count

-0.208

In [58]:
state.apply_action(1)

In [54]:
E=state.observation_tensor()

In [55]:
import numpy as np
E=np.reshape(E[:-1],(2,2,2))

In [57]:
E[:,:,0]

array([[1., 0.],
       [1., 0.]])

In [104]:
[child.explore_count for child in root.children]

[667, 332]

In [107]:
state.get_meanpayoff()

0.984290361404419

In [32]:
import tensorflow as tf
A=tf.random.uniform([5,5,3,6,6]) < 0
B=tf.reduce_any(A,axis=-1)
Z=tf.linalg.diag(~B)
C=A|Z

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [40]:
tf.cast(tf.constant([-0.,5.]),dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>