In [2]:
import pyspiel

In [3]:
game=pyspiel.load_game("mpg(max_moves=50,max_size=100,generator=usgnp,generator_params=30 30 0.3 0.7 -1 1,padding=false,representation=normal)")

In [4]:
state=game.new_initial_environment_state()

In [5]:
state.observation_tensor_shapes_list()

[[30, 30, 2], [1]]

In [6]:
state.count_edges()

485

In [7]:
state.graph_size()

30

In [8]:
E.shape

NameError: name 'E' is not defined

In [9]:
E=E.reshape(state.observation_tensor_shapes_list()[0])

E[:,:,1]

NameError: name 'E' is not defined

In [31]:
state.apply_action(2)

In [32]:
state

13085936220915563836

In [53]:
import numpy as np
A=np.array(state.observation_tensor())
E,s=A[:-1],A[-1]

In [57]:
E=E.reshape(state.observation_tensor_shapes_list()[0])
E[:,:,0]

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.]])

In [19]:
import pandas as pd
df=pd.read_json("stats.jsonl",lines=True)

In [20]:
df

0  \
0                                                 {}   
1                                                 {}   
2  {'start_time': '2023-06-26T00:45:36.482062', '...   
3  {'start_time': '2023-06-26T00:47:18.853107', '...   
4  {'start_time': '2023-06-26T00:49:02.368419', '...   
5  {'start_time': '2023-06-26T00:50:46.122679', '...   
6  {'start_time': '2023-06-26T00:52:29.063244', '...   
7  {'start_time': '2023-06-26T00:54:10.909819', '...   
8  {'start_time': '2023-06-26T00:55:53.082160', '...   

                                                   1  \
0                                                 {}   
1                                                 {}   
2  {'start_time': '2023-06-26T00:45:36.552605', '...   
3  {'start_time': '2023-06-26T00:47:19.672664', '...   
4  {'start_time': '2023-06-26T00:49:02.859706', '...   
5  {'start_time': '2023-06-26T00:50:44.802517', '...   
6  {'start_time': '2023-06-26T00:52:27.951881', '...   
7  {'start_time': '2023-06-26T00:54:09.628702', '...   
8  {'start_time': '2023-06-26T00:55:51.948519', '...   

                                                   2  
0                                                 {}  
1                                                 {}  
2  {'start_time': '2023-06-26T00:45:36.513515', '...  
3  {'start_time': '2023-06-26T00:47:18.744794', '...  
4  {'start_time': '2023-06-26T00:49:00.273266', '...  
5  {'start_time': '2023-06-26T00:50:42.113778', '...  
6  {'start_time': '2023-06-26T00:52:23.545262', '...  
7  {'start_time': '2023-06-26T00:54:06.049684', '...  
8  {'start_time': '2023-06-26T00:55:48.275617', '...

In [1]:
import pyspiel 
from mpg.games.mpg import MeanPayoffGraph
G=MeanPayoffGraph()
G.add_edge(0,1,2)
G.add_edge(1,0,1)

In [42]:
game=pyspiel.load_game("mpg(max_repeats=3,max_size=2,generator=gnp,generator_params=50 1 -1 1)")
state=game.new_initial_state()

In [11]:
import open_spiel.python.algorithms.alpha_zero_mpg.bots as mpg_bots
import open_spiel.python.algorithms.mcts as mcts

2023-06-28 13:02:23.665095: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 13:02:24.237729: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [12]:
uct_c=1
max_simulations=1000
evaluator_=mcts.RandomRolloutEvaluator()
noise=(1,1)
solve=False
bot=mcts.MCTSBot(
        game,
        uct_c,
        max_simulations,
        evaluator_,
        solve=solve,
        dirichlet_noise=None,
        child_selection_fn=mcts.SearchNode.puct_value,
        verbose=False,
        dont_return_chance_node=True)

In [13]:
state.apply_action12)

OpenSpiel exception: /home/ramizouari/Academic/AI/MeanPayOffGames/open_spiel/open_spiel/games/mpg/mpg.cc:139 CHECK_TRUE(environment->graph[current_state].count(move))


SpielError: /home/ramizouari/Academic/AI/MeanPayOffGames/open_spiel/open_spiel/games/mpg/mpg.cc:139 CHECK_TRUE(environment->graph[current_state].count(move))

In [110]:
state=game.new_initial_environment_state()
state.current_player()

0

In [111]:

root=bot.mcts_search(state)

root.total_reward / root.explore_count

-0.208

In [58]:
state.apply_action(1)

In [54]:
E=state.observation_tensor()

In [55]:
import numpy as np
E=np.reshape(E[:-1],(2,2,2))

In [57]:
E[:,:,0]

array([[1., 0.],
       [1., 0.]])

In [104]:
[child.explore_count for child in root.children]

[667, 332]

In [107]:
state.get_meanpayoff()

0.984290361404419

In [32]:
import tensorflow as tf
A=tf.random.uniform([5,5,3,6,6]) < 0
B=tf.reduce_any(A,axis=-1)
Z=tf.linalg.diag(~B)
C=A|Z

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [40]:
tf.cast(tf.constant([-0.,5.]),dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [50]:
import abc

import tensorflow as tf
import mpg.ml.model.gnn as gnn
import mpg.ml.layers.augmentation as aug
import mpg.ml.dataset.reader as reader
import mpg.ml.dataset.generator as generator
import mpg.ml.dataset.utils as utils
import mpg.ml.dataset.transforms as transforms

class LossTransformation(tf.keras.losses.Loss):
    def __init__(self, loss, name=None):
        super(LossTransformation, self).__init__(name=name)
        self.loss = loss
    @abc.abstractmethod
    def call(self, y_true, y_pred):
        pass

class Tanh2Sigmoid(LossTransformation):
    def __init__(self, name=None):
        super(Tanh2Sigmoid, self).__init__(tf.keras.losses.BinaryCrossentropy(name=name), name=name)

    def call(self, y_true, y_pred):
        return self.loss((y_true+1)/2, (tf.sigmoid(y_pred)+1)/2)
def main(argv=()):
    target_path="/run/media/ramizouari/6cf4ec5b-ccaf-4b2a-a40f-75ddfe64af76/HPC/dataset/targets_dense-worker-35347670-0.json"
#target_dataset="/run/media/ramizouari/6cf4ec5b-ccaf-4b2a-a40f-75ddfe64af76/HPC/dataset/targets_dense.json"
    gen=reader.MPGGraphReader("/run/media/ramizouari/6cf4ec5b-ccaf-4b2a-a40f-75ddfe64af76/HPC/dataset/dense",target="all",target_path=target_path,debug=False)
    model = gnn.ResGNN(conv_layers=[32, 16, 1, 32, 16, 1], residual_connections={3: [0], 6: [3, 0]},
                       graph_normalisation=True,
                       masked_softmax=True, ragged_batch=False, weight_normalisation="std",
                       random_connection_probability=0.05,
                       weight_noise_layer=aug.UniformNoise(-0.01, 0.01, name="uniform_noise"))
    sub_model = tf.keras.Model(inputs=model.inputs, outputs=(model.outputs[0]+1)/2)
    
    sub_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss="binary_crossentropy",metrics=["accuracy"])
    sub_model.summary()
    T=transforms.DatasetStackTransforms([transforms.Transposer(),transforms.WithStartingPosition(0,0),transforms.StrategyEncoder(),transforms.BatchDatasetTransform(pad=True,batch_size=32)])
    dataset=T(gen).map(lambda X,Y:(X,(Y[0]+1)/2)).take(16).cache().repeat()
    return sub_model,dataset

In [51]:
model,dataset=main()

(TensorSpec(shape=(2, None, None), dtype=tf.float32, name=None), TensorSpec(shape=(2, 2, None), dtype=tf.float32, name=None))


2023-07-11 15:36:04.089222: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?]
	 [[{{node Placeholder}}]]


Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 environment (InputLayer)       [(None, None, None,  0           []                               
                                 2)]                                                              
                                                                                                  
 state (InputLayer)             [(None,)]            0           []                               
                                                                                                  
 tf.cast_12 (TFOpLambda)        (None,)              0           ['state[0][0]']                  
                                                                                                  
 tf.compat.v1.shape_6 (TFOpLamb  (4,)                0           ['environment[0][0]']      

In [53]:
model.fit(dataset,steps_per_epoch=8,epochs=50)

Epoch 1/50
8/8 [==============================] - 0s 43ms/step - loss: 0.6788 - accuracy: 0.5938
Epoch 2/50
8/8 [==============================] - 0s 37ms/step - loss: 0.6796 - accuracy: 0.5859
Epoch 3/50
8/8 [==============================] - 0s 42ms/step - loss: 0.6786 - accuracy: 0.5938
Epoch 4/50
8/8 [==============================] - 0s 38ms/step - loss: 0.6795 - accuracy: 0.5781
Epoch 5/50
8/8 [==============================] - 0s 41ms/step - loss: 0.6783 - accuracy: 0.5938
Epoch 6/50
8/8 [==============================] - 0s 37ms/step - loss: 0.6802 - accuracy: 0.5820
Epoch 7/50
8/8 [==============================] - 0s 42ms/step - loss: 0.6781 - accuracy: 0.5977
Epoch 8/50
8/8 [==============================] - 0s 36ms/step - loss: 0.6795 - accuracy: 0.5820
Epoch 9/50
8/8 [==============================] - 0s 42ms/step - loss: 0.6780 - accuracy: 0.5938
Epoch 10/50
8/8 [==============================] - 0s 37ms/step - loss: 0.6794 - accuracy: 0.5820
Epoch 11/50
8/8 [============

In [41]:
X,Y=next(iter(dataset))

2023-07-11 15:32:19.657998: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


In [42]:
Y

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([-1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1.,
        1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1., -1., -1.,  1.,
        1., -1., -1., -1.,  1.,  1.], dtype=float32)>

In [45]:
sub_model = tf.keras.Model(inputs=model.inputs, outputs=(model.outputs[0]+1)/2)
    