In [1]:
import pyspiel

In [12]:
game=pyspiel.load_game("mpg(max_moves=50,max_size=100,generator=usgnp,generator_params=3 7 0.3 0.7 -1 1,padding=false,representation=normal)")

In [14]:
state=game.new_initial_environment_state()

In [15]:
state.observation_tensor_shapes_list()

[[7, 7, 2], [1]]

In [16]:
state.count_edges()

23

In [18]:
state.graph_size()

7

In [21]:
E.shape

(18,)

In [22]:
E=E.reshape(state.observation_tensor_shapes_list()[0])

E[:,:,1]

array([[ 0.        ,  0.08456993,  0.        ],
       [-0.88568044,  0.        ,  0.        ],
       [ 0.68452108, -0.15285891,  0.26305676]])

In [31]:
state.apply_action(2)

In [32]:
state

13085936220915563836

In [53]:
import numpy as np
A=np.array(state.observation_tensor())
E,s=A[:-1],A[-1]

In [57]:
E=E.reshape(state.observation_tensor_shapes_list()[0])
E[:,:,0]

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.]])

In [19]:
import pandas as pd
df=pd.read_json("stats.jsonl",lines=True)

In [20]:
df

0  \
0                                                 {}   
1                                                 {}   
2  {'start_time': '2023-06-26T00:45:36.482062', '...   
3  {'start_time': '2023-06-26T00:47:18.853107', '...   
4  {'start_time': '2023-06-26T00:49:02.368419', '...   
5  {'start_time': '2023-06-26T00:50:46.122679', '...   
6  {'start_time': '2023-06-26T00:52:29.063244', '...   
7  {'start_time': '2023-06-26T00:54:10.909819', '...   
8  {'start_time': '2023-06-26T00:55:53.082160', '...   

                                                   1  \
0                                                 {}   
1                                                 {}   
2  {'start_time': '2023-06-26T00:45:36.552605', '...   
3  {'start_time': '2023-06-26T00:47:19.672664', '...   
4  {'start_time': '2023-06-26T00:49:02.859706', '...   
5  {'start_time': '2023-06-26T00:50:44.802517', '...   
6  {'start_time': '2023-06-26T00:52:27.951881', '...   
7  {'start_time': '2023-06-26T00:54:09.628702', '...   
8  {'start_time': '2023-06-26T00:55:51.948519', '...   

                                                   2  
0                                                 {}  
1                                                 {}  
2  {'start_time': '2023-06-26T00:45:36.513515', '...  
3  {'start_time': '2023-06-26T00:47:18.744794', '...  
4  {'start_time': '2023-06-26T00:49:00.273266', '...  
5  {'start_time': '2023-06-26T00:50:42.113778', '...  
6  {'start_time': '2023-06-26T00:52:23.545262', '...  
7  {'start_time': '2023-06-26T00:54:06.049684', '...  
8  {'start_time': '2023-06-26T00:55:48.275617', '...

In [1]:
import pyspiel 
from mpg.games.mpg import MeanPayoffGraph
G=MeanPayoffGraph()
G.add_edge(0,1,2)
G.add_edge(1,0,1)

In [57]:
game=pyspiel.load_game("mpg(max_repeats=3,max_size=2,generator=gnp,generator_params=50 1 -1 1)")
state=game.new_initial_state()

In [58]:
import open_spiel.python.algorithms.alpha_zero_mpg.bots as mpg_bots
import open_spiel.python.algorithms.mcts as mcts

In [59]:
uct_c=1
max_simulations=1000
evaluator_=mcts.RandomRolloutEvaluator()
noise=(1,1)
solve=False
bot=mcts.MCTSBot(
        game,
        uct_c,
        max_simulations,
        evaluator_,
        solve=solve,
        dirichlet_noise=None,
        child_selection_fn=mcts.SearchNode.puct_value,
        verbose=False,
        dont_return_chance_node=True)

In [44]:
state.apply_action(12)

In [61]:
root=bot.mcts_search(state)

In [62]:
root.total_reward / root.explore_count

0.218

In [24]:
state

@@@
@Graph: 
{0: (0, 0.263057) (4, 0.812603) (5, -0.311229) (7, 0.194989) (8, 0.684521) (10, 0.98429) (11, 0.311052) (13, -0.88568) (14, -0.680413) (16, -0.152859) (17, -0.153704) (20, 0.0845699) (23, -0.920862) (27, 0.860862) 
1: (0, 0.158528) (1, -0.708368) (2, -0.425139) (6, 0.115361) (7, 0.390841) (8, 0.580379) (10, -0.110658) (13, 0.129099) (16, -0.707164) (17, -0.699669) (18, -0.960132) (19, 0.108815) (21, 0.374664) (24, -0.223694) (27, 0.857578) (28, -0.640412) (29, -0.49077) 
2: (4, -0.680914) (6, 0.970941) (7, 0.960815) (10, -0.485821) (11, -0.0476629) (13, 0.340131) (14, 0.535543) (17, 0.676366) (18, -0.654885) (19, -0.73994) (20, -0.366541) (21, 0.765722) (22, -0.200392) (24, -0.16425) (27, 0.0318798) (29, -0.620184) 
3: (3, 0.191835) (5, -0.609584) (7, -0.571858) (10, -0.712209) (11, 0.51575) (12, -0.769123) (13, 0.685931) (15, 0.72779) (16, 0.0590172) (17, 0.0805644) (21, 0.06613) (23, -0.767977) (25, 0.90055) (26, 0.595112) (28, -0.443309) (29, -0.009911) 
4: (2, -0.86027

In [54]:
E=state.observation_tensor()

In [55]:
import numpy as np
E=np.reshape(E[:-1],(2,2,2))

In [57]:
E[:,:,0]

array([[1., 0.],
       [1., 0.]])

In [104]:
[child.explore_count for child in root.children]

[667, 332]

In [107]:
state.get_meanpayoff()

0.984290361404419

In [32]:
import tensorflow as tf
A=tf.random.uniform([5,5,3,6,6]) < 0
B=tf.reduce_any(A,axis=-1)
Z=tf.linalg.diag(~B)
C=A|Z

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [40]:
tf.cast(tf.constant([-0.,5.]),dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>